config/routes.rb
Balltracker::Application.routes.draw do
  root 'main#home'

  get '/auth/:provider', :to => 'sessions#auth'
  match '/auth/:provider/callback', :to => 'sessions#auth_success', :via => [:get, :post]
  get '/auth/failure', :to => 'sessions#auth_failure'
  delete '/signout', :to => 'sessions#destroy'

  resources :users, :only => [:index]
  resources :posts do
    resources :comments, :only => [:index, :create, :update, :destroy]
  end

  resources :post_categories, :except => [:new]

  resources :teams, :only => [:index, :create, :update, :destroy]

  resources :seasons do
    collection do
      get 'last'
    end

    resources :rounds
  end

  resources :rounds, :except => [:new, :create] do
    resources :games
  end

  resources :games

  get '/:key', to: 'posts#show_by_key', :as => :post_by_key
end

app/models/season.rb
class Season
  include Mongoid::Document
  @@last_results_calculation_time = {}

  field :title, type: String

  has_and_belongs_to_many :teams, :inverse_of => :seasons
  has_many :rounds, :inverse_of => :season, :dependent => :destroy

  has_many :results, :class_name => 'SeasonResult', :inverse_of => :season, :dependent => :destroy

  def get_results
    if (Time.now - @@last_results_calculation_time.fetch(self.id, Time.new(0))) > 1.minute
      calculate_results
    end

    self.results
  end

  def calculate_results
    results = {}
    cur_date = DateTime.now

    self.teams.each do |t|
      results[t.id] = {
        games: 0,

        scored_goals: 0,
        against_goals: 0,
        scored_against_diff: 0,

        wins: 0,
        loses: 0,
        draws: 0,

        points: 0
      }
    end

    self.rounds.each do |r|
      r.games.each do |g|
        next unless g.completted?
        next unless g.home_goals_number && g.visitor_goals_number

        g.teams.each { |t| results[t.id][:games] += 1 }

        results[g.home_team.id][:scored_goals] += g.home_goals_number
        results[g.home_team.id][:against_goals] += g.visitor_goals_number
        results[g.home_team.id][:scored_against_diff] = g.home_goals_number - g.visitor_goals_number

        results[g.visitor_team.id][:scored_goals] += g.visitor_goals_number
        results[g.visitor_team.id][:against_goals] += g.home_goals_number
        results[g.visitor_team.id][:scored_against_diff] = g.visitor_goals_number - g.home_goals_number


        if g.home_goals_number == g.visitor_goals_number
          g.teams.each do |t|
            results[t.id][:draws] += 1
            results[t.id][:points] += 1
          end
        elsif g.home_goals_number > g.visitor_goals_number
          results[g.home_team.id][:wins] += 1
          results[g.home_team.id][:points] += 3

          results[g.visitor_team.id][:loses] += 1
        else
          results[g.visitor_team.id][:wins] += 1
          results[g.visitor_team.id][:points] += 3

          results[g.home_team.id][:loses] += 1
        end
      end
    end

    results.keys.each do |team_id|
      se = SeasonResult.find_or_initialize_by(season_id: self.id, team_id: team_id)
      se.assign_attributes(results[team_id])
      se.save

      results[team_id] = se
    end

    @@last_results_calculation_time[self.id] = Time.now
    results
  end
end

app/controllers/seasons_controller.rb
class SeasonsController < ApplicationController
  def last
    @season = Season.last
    render :show
  end

  def index
    @seasons = Season.all
  end

  def show
    @season = Season.find(params[:id])
  end

  def new
    @season = Season.new
    @teams = Team.all
  end

  def edit
  end

  def create
    @season = Season.new(season_params)
    @season.teams = Team.all.limit(20)
    if @season.save
      redirect_to @season
    else
      render :new
    end
  end

  def update
  end

  private

  def season_params
    params.require(:season).permit(:title, :begin_date, :end_date)
  end
end

app/helpers/seasons_helper.rb
module SeasonsHelper
  def new_game(round=nil)
    round ? [round, round.games.build] : Game.new
  end
end

app/views/seasons/index.html.haml
%h1
  ყველა სეზონი

%ul.seasons-list
  -if @seasons
    -@seasons.each do |season|
      %li
        =link_to season do
          %h4
            =season.title

.ctrl
  =link_to "New season", new_season_path, class: ['btn', 'btn-primary', 'btn-large']

app/views/seasons/new.html.haml
%h1
  New season

=form_for @season do |f|
  %fieldset
    =f.label :title
    =f.text_field :title

    =f.label :begin_date
    =f.text_field :begin_date

    =f.label :end_date
    =f.text_field :end_date

    =f.collection_select :teams, @teams, :id, :title, :multiple => true

  =f.submit class: ['btn', 'btn-primary', 'btn-large']

app/views/seasons/show.html.haml
%h1
  =@season.title

.rounds-list
  ტურები:
  .btn-group
    -@season.rounds.each do |round|
      =link_to round.number, "#round-#{round.id}", class: ['btn', 'btn-mini']
  =link_to "ტურის დამატება", season_rounds_path(@season), :method => :post, class: ['btn', 'btn-primary', 'btn-mini']

  -@season.rounds.each do |round|
    %a{name: "round-#{round.id}"}
    .round
      %h4
        ="ტური ##{round.number} თამაშები - #{round.games.count}/10"

      %table.games-table.table
        %tbody
          -round.games.each_with_index do |game|
            %tr{class: game.completted? ? 'completted' : ''}
              %a{name: "game-#{game.id}"}
              %td.date
                ="#{format_date_time(game.begin_date)} / #{format_date_time(game.end_date)}"

              %td.home_team_title
                =game.home_team.title
              %td.home_team_image
                =image_tag game.home_team.image.url(:small)

              %td.goals_number
                -if game.completted?
                  ="#{game.home_goals_number}:#{game.visitor_goals_number}"
                -else
                  \---

              %td.visitor_team_image
                =image_tag game.visitor_team.image.url(:small)
              %td.visitor_team_title
                =game.visitor_team.title

              %td.actions
                [
                =link_to 'შეცვლა', edit_game_path(game)
                ][
                =link_to 'x', game, :method => :delete, :confirm => 'Are you sure?'
                ]

      .ctrl
        =link_to "თამაშის დამატება", new_round_game_path(round), class: ['btn', 'btn-primary'] if round.games.count < 10
        -#=link_to "ტურის შეცვლა", edit_round_path(round), class: ['btn', 'btn-warning']
        =link_to "ტურის წაშლა", round, :method => :delete, confirm: 'Are you sure?', class: ['btn', 'btn-danger']

  .ctrl
    =link_to "ტურის დამატება", season_rounds_path(@season), :method => :post, class: ['btn', 'btn-primary', 'btn-large']