config/routes.rb
Balltracker::Application.routes.draw do
  root 'main#home'

  get '/auth/:provider', :to => 'sessions#auth'
  match '/auth/:provider/callback', :to => 'sessions#auth_success', :via => [:get, :post]
  get '/auth/failure', :to => 'sessions#auth_failure'
  delete '/signout', :to => 'sessions#destroy'

  resources :users, :only => [:index]
  resources :posts do
    resources :comments, :only => [:index, :create, :update, :destroy]
  end

  resources :post_categories, :except => [:new]

  resources :teams, :only => [:index, :create, :update, :destroy]

  resources :seasons do
    collection do
      get 'last'
    end

    resources :rounds
  end

  resources :rounds, :except => [:new, :create] do
    resources :games
  end

  resources :games

  get '/:key', to: 'posts#show_by_key', :as => :post_by_key
end

app/models/post_category.rb
class PostCategory
  include Mongoid::Document

  attr_accessor :new_key

  field :key, type: String
  field :title, type: String

  has_many :posts, :inverse_of => :post_category, :dependent => :destroy

  belongs_to :parent, class_name: 'PostCategory', :inverse_of => :children
  has_many :children, class_name: 'PostCategory', :inverse_of => :parent, :autosave => true, :dependent => :destroy

  index({key: 1}, {sparse: true, unique: true})

  before_save :key_if_exists

  def self.parent
    self.where(:parent => nil)
  end

  def self.[](key)
    self.find_by(key: key)
  end

  private

  def key_if_exists
    self.key = new_key unless self.new_key && self.new_key.empty?
  end
end

app/controllers/post_categories_controller.rb
class PostCategoriesController < ApplicationController
  before_action :admin_permissions_required
  before_action :target_post_category_required, :only => [:edit, :update, :destroy]

  def index
    @post_category = PostCategory.new
  end

  def edit
    render :index
  end

  def create
    @post_category = PostCategory.create(post_category_params)

    redirect_to post_categories_path
  end

  def update
    @post_category.update_attributes(post_category_params)

    redirect_to post_categories_path
  end

  def destroy
    @post_category.destroy

    redirect_to post_categories_path
  end

  private

  def post_category_params
    params.require(:post_category).permit(:new_key, :title, :parent_id)
  end

  def target_post_category_required
    @post_category = PostCategory.find(params[:id])
  end
end

app/helpers/post_categories_helper.rb
module PostCategoriesHelper
end

app/views/post_categories/index.html.haml
%h1
  პოსტის კატეგორია

%ul
  -post_categories.each do |category|
    %li
      ="#{category.title} /#{category.key}/"
      [
      =link_to 'შეცვლა', edit_post_category_path(category)
      ]
      [
      =link_to 'x', category, method: :delete, confirm: 'Are you sure?'
      ]
      %ul
        -category.children.each do |c|
          %li
            ="#{c.title} /#{c.key}/"
            [
            =link_to 'შეცვლა', edit_post_category_path(c)
            ]
            [
            =link_to 'x', c, method: :delete, confirm: 'Are you sure?'
            ]

%h2
  კატეგორიის დამატება
  .category-form.form.form-inline
    =form_for @post_category do |f|
      =f.select :parent_id, @post_categories.collect {|parent| [parent.title, parent.id] }, {include_blank: '(Parentless)'}
      =f.text_field :new_key, placeholder: 'გასაღები'
      =f.text_field :title, placeholder: 'სათაური'
      =f.submit class: ['btn', 'btn-primary']