config/routes.rb
Balltracker::Application.routes.draw do
  root 'main#home'

  get '/auth/:provider', :to => 'sessions#auth'
  match '/auth/:provider/callback', :to => 'sessions#auth_success', :via => [:get, :post]
  get '/auth/failure', :to => 'sessions#auth_failure'
  delete '/signout', :to => 'sessions#destroy'

  resources :users, :only => [:index]
  resources :posts do
    resources :comments, :only => [:index, :create, :update, :destroy]
  end

  resources :post_categories, :except => [:new]

  resources :teams, :only => [:index, :create, :update, :destroy]

  resources :seasons do
    collection do
      get 'last'
    end

    resources :rounds
  end

  resources :rounds, :except => [:new, :create] do
    resources :games
  end

  resources :games

  get '/:key', to: 'posts#show_by_key', :as => :post_by_key
end

app/views/layouts/_footer.html.haml
.footer
  &copy;
  =link_to 'Nuclight.org', 'http://nuclight.org'
  (2013-2014)
  .couinters
    %script{:language => "JavaScript", :src => "http://counter.top.ge/cgi-bin/cod?100+91281", :type => "text/javascript"}
    %noscript
      %a{:href => "http://counter.top.ge/cgi-bin/showtop?91281", :target => "_top"}
        %img{:alt => "TOP.GE", :border => "0", :src => "http://counter.top.ge/cgi-bin/count?ID:91281+JS:false"}/

app/views/layouts/_header.html.haml
.container
  =link_to root_path do
    =image_tag 'logo.png', id: 'logo'
    %span#logo-text FCCHELSEA GE

app/views/layouts/_navbar.html.haml
.navbar.navbar-fixed-top.main-nav-bar
  .navbar-inner
    .container
      %a.btn.btn-navbar{:data=>{:toggle=>"collapse", :target=>".nav-collapse"}}
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar

      =link_to root_path, class: 'brand' do
        მთავარი

      .nav-collapse.collapse
        %ul.nav
          -post_categories.select(& lambda {|c| c.children.exists? }).each do |category|
            -if category.children.exists?
              %li.dropdown
                %a.dropdown-toggle{href: '#', data: {toggle: 'dropdown'}}
                  =category.title
                  %b.caret
                %ul.dropdown-menu
                  -category.children.each do |sub_category|
                    %li
                      =link_to sub_category.title, category_path_ex(sub_category)
            -else
              %li
                =link_to category.title, posts_path(:post_category => category.id)


          -if signed_in_user_has_admin_permissions?
            %li.dropdown
              %a.dropdown-toggle{href: '#', data: {toggle: 'dropdown'}}
                ადმინ პანელი
                %b.caret
              %ul.dropdown-menu
                %li
                  =link_to 'ახალი პოსტი', new_post_path
                %li
                  =link_to 'კატეგორიები', post_categories_path
                
                -if current_season
                  %li
                    =link_to current_season.title, current_season
                -else
                  %li
                    =link_to 'ჩემპიონატები', seasons_path

                -#%li
                -#  =link_to 'გუნდები', teams_path
                -#%li
                -#  =link_to 'Users', users_path



        %ul.nav.pull-right
          %li.divider-vertical
          -if user_signed_in?
            %li
              .btn-group
                =link_to signed_in_user.urls['facebook'], class: %w(btn user-link) do
                  .avatar
                    =image_tag signed_in_user.image, class: 'img-rounded'
                  =signed_in_user.nick

                =link_to signout_path, :method => :delete, class: %w(btn btn-primary) do
                  გასვლა
          -else
            %li
              =render 'layouts/social_login'
          %li.divider-vertical

app/views/layouts/_social_login.html.haml
.cosial-login
  =link_to '/auth/facebook', class: %w(btn btn-primary) do
    Enter with Facebook

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Fcchelsea
    = stylesheet_link_tag    "application", media: "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    = yield :social_meta
  %body

    =render 'layouts/navbar'
    =render 'layouts/header'

    .container.master-container
      .master-container-inner
        = yield



      =render 'layouts/footer'

      #fb-root
      :javascript
        (function(d, s, id) {
          var js, fjs = d.getElementsByTagName(s)[0];
          if (d.getElementById(id)) return;
          js = d.createElement(s); js.id = id;
          js.src = "//connect.facebook.net/ge_KA/all.js#xfbml=1&appId=621275447917435";
          fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));